// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { FpjsProvider } from '@fingerprintjs/fingerprintjs-pro-react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log("FpjsProvider initialized");
  return (
    <FpjsProvider
      loadOptions={{
        apiKey: "tlH9DQ3ZOb0IvoOp1qKz",
      }}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </FpjsProvider>
  );
}

