// app/layout.tsx
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


import { FpjsProvider } from '@fingerprintjs/fingerprintjs-pro-react';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  console.log("FpjsProvider initialized");
  return (
    <FpjsProvider
      loadOptions={{
        apiKey: "tlH9DQ3ZOb0IvoOp1qKz",
      }}
    >
      <html lang="en">
        <body>{children}</body>
      </html>
    </FpjsProvider>
  );
}

